### ISSUE TITLE
home sections 10.11.0 truenas

### ISSUE THREAD

**Issue by Kmike17** [IAmParadox27/jellyfin-plugin-home-sections#107]
After updating Jellyfin to 10.11.0 and reinstalling all my plugins I've realized that the plugin isn't working right. The because you watched section is not showing (even after watching a movie) and the watch again section shows all movies alphabetically. Not sure of any bugs these are the only sections that I use on my instance.

**Comment by IAmParadox27** [comment]
That's interesting. I didn't notice any issues with these sections during either my testing or since migrating my own server to 10.11

I'll take a look but I'm not sure there's anything different here, all the logic for each section is unchanged

**Comment by Kmike17** [comment]
Tried uninstalling and reinstalling, no change. Then tried the experimental version, same issue persists. Not sure if it's because I have Jellyfin running on a Tuenas scale system. I've seen there have been issues with Jellyfin 10.11.0 installation on Linux-based systems.

**Comment by archettitechnology** [comment]
same on my truenas, seems that the home-section plugin doesn't see that file-transfomation plugin is installed. this after the 10.11 update. so now i see the home section like the default installation of jellyfin

**Comment by IAmParadox27** [comment]
Can you enable debug logging in file transformation plugin settings restart your server and post your startup logs please

**Comment by Kmike17** [comment]
> same on my truenas, seems that the home-section plugin doesn't see that file-transfomation plugin is installed. this after the 10.11 update. so now i see the home section like the default installation of jellyfin

Initially, that's how mine was I had to uninstall and reinstall all plugins and that's what gave me the error I saw.

**Comment by archettitechnology** [comment]
i have other plug that use file -trasfomation and they are working, so i think is home-section in truens docker

**Comment by archettitechnology** [comment]
[log_20251022.log](https://github.com/user-attachments/files/23050879/log_20251022.log)

This is my log 

Aldo the message from home-section setting when try to clean cache

<img width="893" height="431" alt="Image" src="https://github.com/user-attachments/assets/355c01af-9ab2-4642-8be7-499f8f4f7a3a" />

**Comment by Kmike17** [comment]
> i have other plug that use file -trasfomation and they are working, so i think is home-section in truens docker

Same here.

**Comment by Kmike17** [comment]
Here is my log.

[log_20251022.log.txt](https://github.com/user-attachments/files/23051333/log_20251022.log.txt)

**Comment by NoisyBoyFR** [comment]
I really like this plugin and I admit that I would love to have a French version because my multimedia is in French, but I have the same problems as you. Every time I refresh the page, I get different sections since 10.11. 

I don't know if my information will help, but the sections are sometimes in order, sometimes out of order, sometimes missing, and sometimes the most important ones, such as resuming reading, but I go through other sections .......

Good luck! 

PS: The home page takes a very long time to load, even too long... and you end up giving up.

**Comment by archettitechnology** [comment]
i think @Kmike17 is better to rewrite the issue in 
home sections 10.11.0 Truenas

**Comment by NoisyBoyFR** [comment]
Should I start a new discussion for my problem?

**Comment by archettitechnology** [comment]
maybe yes, idk.. here the problem is for truens that the plugin doesn't work at all. i think is better for @IAmParadox27 to manage with different topic

**Comment by IAmParadox27** [comment]
I'm wondering when you uninstalled and reinstalled did you do a cold reboot of the server between each step or just the restart button in the dash?

**Comment by archettitechnology** [comment]
i only restarted the container

**Comment by Kmike17** [comment]
> I'm wondering when you uninstalled and reinstalled did you do a cold reboot of the server between each step or just the restart button in the dash?

I only restarted in he dashboard.

**Comment by IAmParadox27** [comment]
Can you uninstall the plugin and completely shutdown the jellyfin instance, and start it back up again. 

Can you confirm in scheduled tasks that the Startup Service entry for Home Screen Sections has gone.

Then install the plugin and do the same thing, completely shutdown, start up and check scheduled tasks

**Comment by IAmParadox27** [comment]
I've checked your logs again on my PC and I can confirm this is related to the scheduled task. It is the same for Media Bar and Custom Tabs. Please do the same process for each of my plugins (file transformation is fine) and it should start to work. If not, try running the scheduled task manually and see whether that makes a difference

**Comment by Kmike17** [comment]
Uninstall all of them at the same time or separately? Shutdown in the dashboard followed by a restart in Docker?

**Comment by IAmParadox27** [comment]
Same time is fine - you just need the instance to know they no longer exist so that when you install again the correct scheduled task can be added

In 10.11 Jellyfin changed the format for scheduled tasks in the code so now they have to be re-registered

**Comment by Kmike17** [comment]
Removed all of them except file transformation, shutdown, restarted, and made sure the tasks were removed. Reinstalled and repeated the same thing, but still have the same original issue, no because you watched section appears and watched again, still shows all movies alphabetically.

Are you sure there isn't an issue with file transformation? In the log I shared it looks like it initially threw an error with it on startup.

Here is a new log for review.

[log_20251022.log](https://github.com/user-attachments/files/23062553/log_20251022.log)

**Comment by IAmParadox27** [comment]
No FT is working correctly as seen by these logs at the end of your latest log

```
[2025-10-22 14:16:56.096 -07:00] [INF] [9] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'main.jellyfin.bundle.js' with ID 'c83d86bb-a1e0-4c35-a113-e2101cf4ee6b'
...
[2025-10-22 14:16:59.642 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'index.html' with ID '9340b171-0ae4-4d13-9970-9c4c4feba227'
[2025-10-22 14:16:59.643 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'userpluginsettings.html' with ID 'a837996a-2f73-4ad2-9467-e0410222d36f'
[2025-10-22 14:16:59.643 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'user-plugin.undefined.chunk.js' with ID '345a80b2-2ac2-42f5-834c-809947778a64'
[2025-10-22 14:16:59.643 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'user-plugin-index-html.undefined.chunk.js' with ID '47a40f72-1af9-47b9-a2eb-e073317be4b0'
[2025-10-22 14:16:59.643 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'main.jellyfin.bundle.js' with ID '898bd8c0-70fa-4f63-a4e8-bf16de51dfe4'
[2025-10-22 14:16:59.645 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'main.jellyfin.bundle.js' with ID '6e4bced9-d332-4b95-93f3-b82f088f56ab'
[2025-10-22 14:16:59.645 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'runtime.bundle.js' with ID 'a3530fb2-6d2f-4894-8ca7-691c4e98d1ed'
...
[2025-10-22 14:16:59.854 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'index.html' with ID '73833d5f-0bcb-45dc-ab8b-7ce668f4345d'
...
[2025-10-22 14:17:00.744 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'index.html' with ID 'e531b5a0-5493-42b0-b632-619e2d06db5c'
[2025-10-22 14:17:00.745 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for '56213\.[^.]+\.chunk\.js' with ID 'ea4045f3-6604-4ba4-9581-f91f96bbd2ae'
...
[2025-10-22 14:17:01.036 -07:00] [INF] [12] Jellyfin.Plugin.MediaBar.MediaBarPlugin: MediaBar Startup. Registering file transformations.
[2025-10-22 14:17:01.039 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'index.html' with ID '0dfac9d7-d898-4944-900b-1c1837707279'
[2025-10-22 14:17:01.039 -07:00] [INF] [12] Jellyfin.Plugin.FileTransformation.FileTransformationPlugin: Received transformation registration for 'avatars/list.txt' with ID '8d374d6b-3c5b-464a-a2a2-96e92fa81345'
...
[2025-10-22 14:17:03.992 -07:00] [INF] [9] Main: Startup complete 0:00:09.7568881
```

Previously there was only 1 plugin registering a transformation (the first one) in that list is the same as before. So at the very least that issue is now solved. What client are you using to test the sections?

**Comment by IAmParadox27** [comment]
Now that these transformations have been registered, can you try the cache trick from the FAQ again and see whether that's resolve it.

**Comment by Kmike17** [comment]
> Aldo the message from home-section setting when try to clean cache
> 
> <img alt="Image" width="893" height="431" src="https://private-user-images.githubusercontent.com/231737992/504117018-355c01af-9ab2-4642-8be7-499f8f4f7a3a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExNzE2MDIsIm5iZiI6MTc2MTE3MTMwMiwicGF0aCI6Ii8yMzE3Mzc5OTIvNTA0MTE3MDE4LTM1NWMwMWFmLTlhYjItNDY0Mi04YmU3LTQ5OWY4ZjRmN2EzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyMlQyMjE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjBkMjUwMzUwNDJjNWFlNWYxYzM2ZjYxNTcwZmEzMWNkMDBmOWJlMDgzMjdkYmRiYzk1NmJkOWQ3ZWQ2ZmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4_ZnyxKupEKhmthzBoShCwCmtxs3o_mGatiYN8qOnBY">

I'm testing it on Android, iOS, and the web portal. I've already tried the cache-clearing trick. I also still get this error when attempting to clear the cache in the plugin settings.

**Comment by IAmParadox27** [comment]
That is not the cache trick. Please refer to the FAQ in the readme. There is another issue #91 relating to the cache message being incorrect. That functionality, isn't working 100% correctly.

As an aside, you won't see changes on Android or iOS until their internal caches are refreshed (usually takes about a day)

**Comment by Kmike17** [comment]
By cache trick, you mean go to developer tools and disable cache in the network tab, then refresh, right? That's what I did, no change.

**Comment by IAmParadox27** [comment]
Yeah that's what I meant. Damn, I was really expecting that to work.

Are you in the JellyfinCommunity discord? https://www.reddit.com/r/JellyfinCommunity/comments/1lrl1mo/join_the_rjellyfincommunity_discord_server/

If you're in there (or want to join to see if we can solve quicker) @ Paradox in there and I'll start a thread in the troubleshooting channel to get us moving, hopefully whatever findings we have we can report back here.

Can you also confirm for me the exact symptoms you're seeing, is the plugin working _at all_ i.e. are some of the sections appearing? Does the home page populate as if the plugin wasn't installed or does it visibly change in some way? Are there sections missing (and details of the sections) etc

**Edit: For the potential notification to the user "Paradox" I apologise for the @**

**Comment by Kmike17** [comment]
I joined the Discord same username Kmike17. 

The home page does change when I add/remove sections, but they just don't always look right. I attached a few pictures to show what I have selected and how it shows on the home page.

<img width="2542" height="1272" alt="Image" src="https://github.com/user-attachments/assets/ded5b7d4-dc44-4b0c-8323-6d735f224d70" />
The watch again shows every movie alphabetically. I haven't watched any of those movies yet.
<img width="557" height="1189" alt="Image" src="https://github.com/user-attachments/assets/49458c4e-6be8-48d2-9f23-f370fcc2ad8f" />

**Comment by archettitechnology** [comment]
after force the run of schedule task now is partially working but still some buggy

**Comment by IAmParadox27** [comment]
Rather than just running the scheduled task, how about following the steps above to get the scheduled task to be setup and work correctly, let me know how it behaves after the scheduled task has run for itself. And always do a cold reboot (not dashboard) when dealing with my plugins and issues like this

**Comment by archettitechnology** [comment]
yes with reinstall and cold reboot of the container the plugin start working, the bug now is the section not correctly showing and the loading logo there isn't

**Comment by IAmParadox27** [comment]
There was a separate bug with Because you watched section which I've fixed and will be rolling out an update to shortly. As you now have the plugin at least working on 10.11 I'm going to close this issue expect the fix to the other issues in 2.4.2.0
