### ISSUE TITLE
[Bug] recently added movies and shows display wrong items.

### ISSUE THREAD

**Issue by elechtma** [IAmParadox27/jellyfin-plugin-home-sections#125]
### Affirmations

- [x] I have checked there are no existing issues open or closed my issue would duplicate
- [x] I have read the FAQ section on the readme and confirm my issue doesn’t relate to any steps there or those steps didn’t work

### Description

Starting yesterday these two sections are displaying old media that was added long ago, not the correct recently added media. I am using the latest plugin versions and jellyfin 10.10.7. 

### Reproduction Steps

Tried restarting server. Enabling and disabling home screen sections. Seems to have popped up with most recent plugin version. Uninstalling Home Screen sections fixes this while maintaining the sections, but reinstalling brings the issue back. 

### Expected Behaviour

should displayed most recently added media. 

### Server Version

10.10.7

### Server OS

docker container

### Plugin Version

2.4.7.0

### File Transformation Version

2.4.1.0

**Comment by hmfaysal** [comment]
Facing the same issue, hope this gets resolved soon

**Comment by IAmParadox27** [comment]
Fixed in 2.4.8.0

**Comment by elechtma** [comment]
> Fixed in 2.4.8.0

Thank you! I'm still seeing this issue persisting for shows. But it's fixed for movies.

**Comment by hmfaysal** [comment]
> Thank you! I'm still seeing this issue persisting for shows. But it's fixed for movies.

Yes, thank you, and same problem, fixed for movies, not for the shows

**Comment by IAmParadox27** [comment]
> Can you do me a favour, it’s going to sound counter intuitive, but can you disable HSS and go have a look at the recently added in shows section by default and see how that’s ordered, I spent a lot of time comparing my data sets to ensure they married up, so it’s odd that it’s still not for you

I posted that in one of the discords I'm in that was also reporting the issue. Can you take a look too and see (and maybe show) the differences please

**Comment by IAmParadox27** [comment]
Please also check your "all episodes" page sorted by date added descending. Check the order of the shows listed there, ignoring duplicate shows

**Comment by maxt91** [comment]
Just adding that i have checked sorting and blowing up the cache. No changes to the outcome

**Comment by IAmParadox27** [comment]
I've pushed an update which has done debug logging to help figure out what's wrong. If someone could update and post their logs after they've requested the homepage that would be great

The cache wouldn't have helped here the results aren't cached

**Comment by elechtma** [comment]
> I've pushed an update which has done debug logging to help figure out what's wrong. If someone could update and post their logs after they've requested the homepage that would be great
> 
> The cache wouldn't have helped here the results aren't cached

There are hundreds of log lines which are all essentially the same - date is showing up as 1/1/0001 (I've edited out the show and episode names for privacy):

[2025-11-01 09:01:57.192 -04:00] [INF] [16] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'example' has been sorted based on episode 'example episode' which has date created of: 1/1/0001 12:00:00 AM.

**Comment by IAmParadox27** [comment]
> > I've pushed an update which has done debug logging to help figure out what's wrong. If someone could update and post their logs after they've requested the homepage that would be great
> > 
> > The cache wouldn't have helped here the results aren't cached
> 
> There are hundreds of log lines which are all essentially the same - date is showing up as 1/1/0001 (I've edited out the show and episode names for privacy):
> 
> [2025-11-01 09:01:57.192 -04:00] [INF] [16] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'example' has been sorted based on episode 'example episode' which has date created of: 1/1/0001 12:00:00 AM.

That's weird that should be sorted to the end of the list and not be chosen. Can I wonder if it's using a different value than DateAdded for you. I'll investigate

**Comment by IAmParadox27** [comment]
Just realised you said all of them are like that. Yeah okay I need to check against that and use a different field

Can you check the metadata for one of the episodes in the list and see what the data comes back with

**Comment by elechtma** [comment]
> Just realised you said all of them are like that. Yeah okay I need to check against that and use a different field
> 
> Can you check the metadata for one of the episodes in the list and see what the data comes back with

When I check one example episode its date added is Feb 4, 2023 in metadata.

**Comment by hmfaysal** [comment]
I found the logs, here they are, I think the date or dateformat is the culprit, idk, kindly take a look at 1/1/0001 12:00:00 AM timestamps, using jellyfin 10.10.7.

```jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'The Office' has been sorted based on episode 'The.Office.S09E26' which has date created of: 1/1/0001 12:00:00 AM.
jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'Fargo' has been sorted based on episode 'Before the Law' which has date created of: 1/1/0001 12:00:00 AM.
jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'WandaVision' has been sorted based on episode 'Previously On' which has date created of: 1/1/0001 12:00:00 AM.
jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'Tom Clancy's Jack Ryan' has been sorted based on episode 'Tertia Optio' which has date created of: 1/1/0001 12:00:00 AM.
jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'Chuck' has been sorted based on episode 'Chuck Versus the Frosted Tips' which has date created of: 1/1/0001 12:00:00 AM.
jellyfin  | [21:46:12] [INF] [92] Jellyfin.Plugin.HomeScreenSections.HomeScreen.Sections.RecentlyAdded.RecentlyAddedShowsSection: Show 'MINDHUNTER' has been sorted based on episode 'Episode 2' which has date created of: 1/1/0001 12:00:00 AM.
```

On an added note, Recently Added Shows works correctly with Jellyfin 10.11.1. But the home sections plugin is extremely slow on the newer version of jellyfin. The api calls are extremely sluggish

**Comment by IAmParadox27** [comment]
> But the home sections plugin is extremely slow on the newer version of jellyfin. The api calls are extremely sluggish

This is likely a result of the debug code I've added unfortunately, I'm taking a look tonight and hopefully will have a fix incoming soon. At which point I'll remove that code that's exacerbating the speed issue.

Also, it is known that there are speed issues across the board in 10.11.x which have been reported a couple times on jellyfin/jellyfin

**Comment by IAmParadox27** [comment]
I've found the issue and pushing a change that will fix it now. Thanks for the 10.10.7 tip that was really useful in helping me find the issue. It seems it was unique to 10.10.7 which is why I wasn't seeing it as my test environment is based on 10.11.x

**Comment by IAmParadox27** [comment]
This should be resolved in 2.4.10.0, please let me know if you're experiencing any issues with the fix on this ticket and I'll reopen

**Comment by elechtma** [comment]
Fixed! Amazing. Thanks for the work on this!
